.TH "Q2PRO" "6" 
.SH "NAME" 
Q2PRO \(em enhanced Quake 2 engine 
.SH "SYNOPSIS" 
.PP 
\fBq2pro\fR [\fB+command \fIarguments\fR\fP]  
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the \fBq2pro\fR program.
.PP 
Q2PRO is a Quake 2 engine modification designed for online play,
fully compatible with original Quake 2 clients and servers.
.PP
Q2PRO features enhanced graphical console, support for JPEG/PNG textures
and MD3 models, network protocol optimizations, freely resizable main window,
increased security and overall performance, basic built-in demo editing
capabilities, built-in server and demo browsers.
.PP
This version of Q2PRO requires a 3D graphics accelerator to play.
Q2PRO uses SDL for video output and SDL/OSS for sound output.
.SH "OPTIONS" 
.PP 
Commands given on the command line start with a `+', and continue until
another `+' or end of line. Variables given on command line override those
given in normal configuration files. If the variable does not exist,
it will be created for future use. Some examples of possible commands follow.
.IP "\fB+set dedicated 1\fP" 7
Start in dedicated server mode with no graphical output. 
.IP "\fB+set deathmatch 1\fP" 7
Enable deathmatch mode (no monsters, etc). 
.IP "\fB+exec config.cfg\fP" 7
Execute the specified configuration file. 
.IP "\fB+map q2dm1\fP" 7
Spawn the server on the given map. 
.IP "\fB\-\-version\fP" 7
Show version and exit. 
.SH "FILES" 
.PP
.IP "\fB/etc/default/q2pro\fP" 7
System wide configuration file. The first one to be executed.
.IP "\fB/usr/share/games/quake2\fP" 7
Root of the static Quake 2 game data hierarchy.
.IP "\fB/usr/lib/games/quake2\fP" 7
Quake 2 game mod shared libraries.
.IP "\fB~/.q2pro\fP" 7
User's local data hierarchy. Overrides system hierarchy.
Any dynamic data Q2PRO produces (savegames, screenshots, demos, etc)
is written here.

.SH "BUGS" 
.PP 
There are a lot more commands and variables, registered dynamically as
various subsystems are loaded. They are not yet documented here.
.PP 
Q2PRO graphical menu subsystem is incomplete.
.SH "AUTHOR" 
.PP 
Quake 2 engine was written by ID Software, Inc. 
Q2PRO was written by Andrey Nazarov <skuller@skuller.ath.cx>. 
.PP 
This manual page was written by Andrey Nazarov <skuller@skuller.ath.cx> for 
the \fBDebian\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any  
later version published by the Free Software Foundation. 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common-licenses/GPL. 
 
